---
abstract: 'Affine Transformation to map 2D coordinates to other 2D coordinates'
author:
  - 'Marc Liyanage <liyanage@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geometry-AffineTransform
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/liyanage/perl-modules.git
version: 1.4
