--- #YAML:1.0
name:                Geometry-AffineTransform
version:             1.0
abstract:            Maps 2D coordinates to other 2D coordinates
license:             ~
author:              
    - Marc Liyanage <reg.cpan@entropy.ch>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::Class:                   0.28
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
