--- #YAML:1.0
name:                Geometry-AffineTransform
version:             1.2
abstract:            Affine Transformation to map 2D coordinates to other 2D coordinates
license:             ~
author:              
    - Marc Liyanage <liyanage@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Hash::Util:                    0
    Math::Trig:                    0
    Test::Class:                   0.28
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
